[logger]
level = "INFO"
representation = "TEXT"
logs_file_path = "./logging/logging.txt"

[storage]
type = "postgres"

[storage.database]
host = "localhost"
port  = "5432"
db_name  = "calendar_db"
sslmode = "disable"
max_conns = 5
min_conns = 3
max_conn_lifetime = "1h"
max_conn_idle_time = "1m"


[server_http]
host = "localhost"
port = "8080"
read_timeout = "10s"
write_timeout = "10s"

[server_grpc]
host = "localhost"
port = "50051"
max_connection_idle = "5m"
max_connection_age = "1h"
time = "1m"
timeout = "10s"