[logger]
level = "INFO"
representation = "TEXT"

[rabbit_scheduler]
host = "localhost"
port = 5672
heartbeat = "30s"
exchange_name = "notification"
queue_name = "notification"
exchange_type = "direct"
durable_exchange = true
durable_queue = true
auto_delete_exchange = false
auto_delete_queue = false
routing_key = "notification"
delivery_mode     = 2